name: Scripted maintenance

on: [ push, pull_request_target ]

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Run clang-format
      run: find -type f \( -name *.h -o -name *.cpp \) | xargs clang-format-12 -style=file -i

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: maintenance
